os: Visual Studio 2015
# Build worker image (VM template)
image: Visual Studio 2015


branches:
  only:
    - master
    - /dev.*/
    - /release-.*/


environment:
  PY_PYTHON: 3.7-32
  github_access_token:
    secure: "ogfTv7V0xR13ETjrC+koS7ZURfl0KLRfwcjYBexoiB1gcc5pppO/H42BopJWl0ua"


install:
  # NSIS Paths
  # https://www.appveyor.com/docs/build-environment/#tools
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS


build_script:
    # 32-bit version
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - C:\Python37\python.exe -m venv .venv32
  - call ".venv32\Scripts\activate.bat"
  - py -m pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - invoke build
  - deactivate
  # 64-bit version
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - C:\Python37-x64\python.exe -m venv .venv64
  - call ".venv64\Scripts\activate.bat"
  - py -m pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - invoke build


artifacts:
  - path: scripts\Bookworm*setup.exe
  - path: scripts\Bookworm*update.bundle


on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("release-")) {
        echo "Updating version information for this release." 
        git config --global credential.helper store
        Add-Content "$HOME\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
        git config --global user.email "musharraf.omer@gmail.com"
        git config --global user.name "mush42"
        git add docs/current_version.json
        git add docs/js/version_provider.js
        git commit -m "Successful build. Automatically updating version files."
        git push origin "HEAD:$env:APPVEYOR_REPO_BRANCH"
        echo "New version info has been pushed to remote."
      }


deploy:
  release: "Bookworm Release (Build v$(appveyor_build_version))"
  description: "Uploaded from appveyor by the build bot"
  provider: GitHub
  auth_token:
    secure: "ogfTv7V0xR13ETjrC+koS7ZURfl0KLRfwcjYBexoiB1gcc5pppO/H42BopJWl0ua"
  artifact: /Bookworm-.*-setup\.exe/, /Bookworm-.*-update\.bundle/
  draft: true
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
