
branches:
  only:
    - master

# Build worker image (VM template)
image: Visual Studio 2017
  
environment:
 PY_PYTHON: 3.7-32

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

install:
  # MSVC Paths
  # https://www.appveyor.com/docs/lang/cpp/#visual-studio
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  # NSIS Paths
  # https://www.appveyor.com/docs/build-environment/#tools
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS

build_script:
    # 32-bit version
  - C:\Python37\python.exe -m venv .venv32
  - call ".venv32\Scripts\activate.bat"
  - py -m pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - invoke build
  - deactivate
  # 64-bit version
  - C:\Python37-x64\python.exe -m venv .venv64
  - call ".venv64\Scripts\activate.bat"
  - py -m pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - invoke build

artifacts:
  - path: scripts\Bookworm*setup.exe
