title: Bookworm
url: "https://mush42.github.io"
baseurl: "/bookworm"
timezone: "Africa/Khartoum"
description: "The universally accessible e-book reader."
keywords: "accessibility, a11y, e-book, readers, nvda, blind, pdf, epub, universal access, screen reader, blind, visually-impaired"
meta_author: Musharraf Omer

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: "Musharraf Omer"

social:
  - title: twitter
    url: "https://twitter.com/mush42/"
  - title: github
    url: "http://github.com/mush42/bookworm/"

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-tactile

# App download details
app:
  intro: "The fully-featured, accessible e-book reader."
  version: "0.1b1"
